name: voice_message_package
description: Flutter package to play/puase voice message in chat messengers.
version: 2.2.3
homepage: https://mehran.monster/

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  just_audio: ^0.9.42
  syncfusion_flutter_sliders: ^25.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
